"""PDF imports: bounded extraction, explicit document states, optional OCR, AI indexing, cleanup.

Documents are synthetic and generated by ``tests/pdf_fixtures.py``. Tests marked
``real_ocr`` run only where Tesseract with the configured languages is installed (the OCR worker
image); elsewhere OCR is either reported as unavailable or replaced by a labelled fake engine.
"""

from __future__ import annotations

import sys
import uuid
from typing import Any

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import func, select
from sqlalchemy.orm import Session, sessionmaker

from app.ai.models import EvidenceIndexState
from app.ai.retrieval import retrieve
from app.cases.models import Case
from app.config import Settings
from app.evidence.models import EvidenceObject
from app.evidence.storage import EvidenceStorage
from app.imports import documents, documents_job
from app.imports.jobs import ProcessingContext
from app.imports.models import ProcessingJob, ProcessingStatus
from app.imports.runner import execute_job
from tests import pdf_fixtures
from tests.ai_helpers import run_ai, run_indexing
from tests.conftest import browser_headers, create_case

INTEGRATION = pytest.mark.integration


def _context(
    factory: sessionmaker[Session], settings: Settings, **overrides: Any
) -> ProcessingContext:
    return ProcessingContext(
        session_factory=factory,
        storage=EvidenceStorage(settings.evidence_storage_path),
        settings=settings.model_copy(update=overrides) if overrides else settings,
        worker_name="test-worker",
    )


def _upload(client: TestClient, csrf: str, case_id: object, content: bytes, **fields: str) -> Any:
    return client.post(
        f"/api/v1/cases/{case_id}/imports/documents",
        files={"file": (fields.pop("filename", "report.pdf"), content, "application/pdf")},
        data={"import_origin": "Synthetic PDF written by the test suite", **fields},
        headers=browser_headers(csrf),
    )


def _run(factory: sessionmaker[Session], settings: Settings, job_id: str, **overrides: Any) -> str:
    return execute_job(_context(factory, settings, **overrides), uuid.UUID(job_id))


def _job(client: TestClient, case_id: object, job_id: str) -> dict[str, Any]:
    response = client.get(f"/api/v1/cases/{case_id}/processing-jobs/{job_id}")
    assert response.status_code == 200, response.text
    body: dict[str, Any] = response.json()
    return body


def _derived_text(settings: Settings, factory: sessionmaker[Session], evidence_id: str) -> str:
    with factory() as db:
        row = db.get(EvidenceObject, uuid.UUID(evidence_id))
        assert row is not None
        return (
            EvidenceStorage(settings.evidence_storage_path)
            .read_verified(row.storage_key, row.sha256, row.size_bytes)
            .decode()
        )


@pytest.fixture
def no_tesseract(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(documents, "_tesseract_binary", lambda: None)


# --- Child process and helpers (no database) -------------------------------------------------


def test_child_process_timeout_is_reported_not_raised_through() -> None:
    with pytest.raises(documents.ChildFailedError) as caught:
        documents.run_child(
            [],
            b"",
            timeout=1,
            memory_mb=256,
            executable=[sys.executable, "-c", "import time; time.sleep(10)"],
        )
    assert caught.value.code == "timeout"


@pytest.mark.skipif(sys.platform != "linux", reason="address-space limits are enforced on Linux")
def test_child_memory_limit_stops_an_oversized_allocation() -> None:
    with pytest.raises(documents.ChildFailedError) as caught:
        documents.run_child(
            [],
            b"",
            timeout=20,
            memory_mb=256,
            executable=[sys.executable, "-c", "bytearray(2 * 1024 ** 3)"],
        )
    assert caught.value.code in ("child_error", "resource_limit")


def test_page_map_points_at_each_page_text() -> None:
    records = [
        documents_job.PageRecord(page=1, status="text", text="Birinci sayfa"),
        documents_job.PageRecord(page=2, status="image_only"),
        documents_job.PageRecord(page=3, status="text", text="  Third page  "),
    ]
    text, page_map, truncated = documents_job._build_text(records, "text", 10_000)
    assert not truncated
    assert [entry["page"] for entry in page_map] == [1, 3]
    for entry, expected in zip(page_map, ["Birinci sayfa", "Third page"], strict=True):
        assert text[entry["char_start"] : entry["char_end"]] == expected
    assert text.startswith("[Page 1]\nBirinci sayfa")
    short, short_map, cut = documents_job._build_text(records, "text", 30)
    assert cut
    assert len(short) <= 30
    assert len(short_map) == 1


def test_citation_page_lookup_uses_the_page_map() -> None:
    from app.ai.service import page_for_offset

    metadata = {
        "page_map": [
            {"page": 1, "char_start": 9, "char_end": 20},
            {"page": 4, "char_start": 31, "char_end": 50},
        ]
    }
    assert page_for_offset(metadata, 0) == 1  # inside the "[Page 1]" header
    assert page_for_offset(metadata, 15) == 1
    assert page_for_offset(metadata, 40) == 4
    assert page_for_offset(metadata, 60) is None
    assert page_for_offset({}, 5) is None
    assert page_for_offset({"page_map": "broken"}, 5) is None


# --- End to end -------------------------------------------------------------------------------


@INTEGRATION
def test_text_pdf_is_extracted_with_page_references_and_indexed_for_ai(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
) -> None:
    case = create_case(client, authed)
    other = create_case(client, authed, title="Other case")
    with db_session_factory() as db:
        assert (
            db.scalar(select(Case.ai_mode).where(Case.id == uuid.UUID(case["id"]))) == "local_only"
        )
    pdf = pdf_fixtures.text_pdf(
        ["Registry summary for ornek.example", "Registrant: Synthetic Holding"],
        ["Hosting moved to 203.0.113.9 in March"],
    )
    response = _upload(client, authed, case["id"], pdf, ocr="if_needed")
    assert response.status_code == 202, response.text
    body = response.json()
    assert body["evidence"]["kind"] == "pdf"
    assert body["evidence"]["content_type"] == "application/pdf"
    assert body["job"]["options"] == {"ocr": "if_needed"}

    assert _run(db_session_factory, settings, body["job"]["id"]) == "completed"
    job = _job(client, case["id"], body["job"]["id"])
    result = job["result"]
    assert result["document_state"] == "text_extracted"
    assert result["pages_total"] == 2
    assert result["page_status_counts"] == {"text": 2}
    assert result["ocr"]["status"] == "not_needed"
    assert result["parser_versions"]["pypdf"]
    assert [item["page_part"] for item in job["derived_evidence"]] == ["text_layer"]

    derived_id = job["derived_evidence"][0]["id"]
    text = _derived_text(settings, db_session_factory, derived_id)
    detail = client.get(f"/api/v1/cases/{case['id']}/evidence/{derived_id}").json()
    evidence = detail["evidence"]
    assert evidence["derived_from_evidence_id"] == body["evidence"]["id"]
    assert evidence["acquisition_method"] == "authorized_import"
    metadata = evidence["collection_metadata"]
    assert metadata["text_origin"] == "embedded_text_layer"
    assert metadata["source_sha256"] == body["evidence"]["sha256"]
    second_page = metadata["page_map"][1]
    assert second_page["page"] == 2
    assert text[second_page["char_start"] : second_page["char_end"]] == (
        "Hosting moved to 203.0.113.9 in March"
    )

    # The original PDF is never decoded for preview; the derived text is.
    original_preview = client.get(
        f"/api/v1/cases/{case['id']}/evidence/{body['evidence']['id']}/preview"
    ).json()
    assert original_preview["previewable"] is False
    derived_preview = client.get(f"/api/v1/cases/{case['id']}/evidence/{derived_id}/preview").json()
    assert "203.0.113.9" in derived_preview["text"]

    # Case-scoped retrieval finds the extracted text; another case does not.
    with db_session_factory() as db:
        state = db.scalar(
            select(EvidenceIndexState).where(
                EvidenceIndexState.evidence_id == uuid.UUID(derived_id)
            )
        )
        assert state is not None
    run_indexing(settings, db_session_factory, case["id"])
    run_indexing(settings, db_session_factory, other["id"])
    with db_session_factory() as db:
        found = retrieve(db, uuid.UUID(case["id"]), "203.0.113.9 hosting", top_k=5)
        assert found.chunks
        assert found.chunks[0].evidence_id == uuid.UUID(derived_id)
        elsewhere = retrieve(db, uuid.UUID(other["id"]), "203.0.113.9 hosting", top_k=5)
        assert all(chunk.evidence_id != uuid.UUID(derived_id) for chunk in elsewhere.chunks)
    search = client.get(f"/api/v1/cases/{case['id']}/ai/search", params={"q": "203.0.113.9"})
    assert any(hit["evidence_id"] == derived_id for hit in search.json()["hits"])

    # A question in the local-only case is answered locally and cites the page of the PDF.
    conversation = client.post(
        f"/api/v1/cases/{case['id']}/ai/conversations", json={}, headers=browser_headers(authed)
    ).json()
    run = client.post(
        f"/api/v1/cases/{case['id']}/ai/conversations/{conversation['id']}/questions",
        json={"question": "Where was hosting moved in March?"},
        headers=browser_headers(authed),
    ).json()
    assert run["requested_location"] == "local"
    assert run_ai(settings, db_session_factory, run["id"]) == "completed"
    finished = client.get(f"/api/v1/cases/{case['id']}/ai/runs/{run['id']}").json()
    assert finished["processing_location"] == "fixture"
    conversation_url = f"/api/v1/cases/{case['id']}/ai/conversations/{conversation['id']}"
    messages = client.get(conversation_url).json()["messages"]
    answer = next(m for m in messages if m["ai_run_id"] == run["id"] and m["role"] == "assistant")
    cited = [
        citation["citation_id"]
        for claim in answer["answer"]["claims"]
        for citation in claim.get("citations", [])
    ]
    assert cited, answer["answer"]
    passages = [
        client.get(f"/api/v1/cases/{case['id']}/ai/citations/{cid}").json()["passage"]
        for cid in cited
    ]
    on_page_two = [p for p in passages if p and p["evidence_id"] == derived_id]
    assert on_page_two
    assert on_page_two[0]["page"] == 2
    assert on_page_two[0]["text_origin"] == "embedded_text_layer"
    assert on_page_two[0]["derived_from_evidence_id"] == body["evidence"]["id"]
    assert "203.0.113.9" in on_page_two[0]["passage"]


@INTEGRATION
def test_document_states_are_explicit_and_derive_nothing_when_unreadable(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
) -> None:
    case = create_case(client, authed)
    expectations = [
        (pdf_fixtures.encrypted_pdf(), "pdf_encrypted", "encrypted"),
        (pdf_fixtures.malformed_pdf(), "pdf_malformed", "malformed"),
    ]
    for pdf, code, state in expectations:
        body = _upload(client, authed, case["id"], pdf).json()
        assert _run(db_session_factory, settings, body["job"]["id"]) == "failed"
        job = _job(client, case["id"], body["job"]["id"])
        assert job["status"] == "failed"
        assert job["error_code"] == code
        assert job["result"]["document_state"] == state
        assert job["derived_evidence"] == []
        # The original stays available and intact.
        detail = client.get(f"/api/v1/cases/{case['id']}/evidence/{body['evidence']['id']}")
        assert detail.json()["integrity"]["status"] == "verified"

    owner_only = _upload(client, authed, case["id"], pdf_fixtures.encrypted_pdf("", "owner")).json()
    assert _run(db_session_factory, settings, owner_only["job"]["id"]) == "completed"
    job = _job(client, case["id"], owner_only["job"]["id"])
    assert any("empty user password" in item for item in job["result"]["limitations"])

    refused = _upload(client, authed, case["id"], b"<html><script>alert(1)</script></html>")
    assert refused.status_code == 422
    assert refused.json()["detail"]["code"] == "unsupported_document_type"


@INTEGRATION
def test_hostile_pdf_actions_are_inert_and_text_is_stored_as_plain_text(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
) -> None:
    case = create_case(client, authed)
    body = _upload(
        client, authed, case["id"], pdf_fixtures.hostile_pdf(), filename="<img src=x>.pdf"
    ).json()
    assert body["evidence"]["original_filename"] == "<img src=x>.pdf"
    assert _run(db_session_factory, settings, body["job"]["id"]) == "completed"
    job = _job(client, case["id"], body["job"]["id"])
    derived = job["derived_evidence"][0]
    assert derived["content_type"] == "text/plain; charset=utf-8"
    text = _derived_text(settings, db_session_factory, derived["id"])
    assert "<script>alert(1)</script>" in text  # kept verbatim as text, never rendered
    assert "198.51.100.7" not in text  # link and JavaScript targets are not extracted or followed
    download = client.get(f"/api/v1/cases/{case['id']}/evidence/{body['evidence']['id']}/content")
    assert download.headers["content-type"] == "application/octet-stream"
    assert download.headers["content-security-policy"] == "sandbox; default-src 'none'"


@INTEGRATION
def test_image_only_pages_without_ocr_engine_give_an_actionable_partial_state(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
    no_tesseract: None,
) -> None:
    case = create_case(client, authed)
    pdf = pdf_fixtures.build_pdf(
        [{"text": ["A page with a real text layer here"]}, {"image": pdf_fixtures.noise_image()}]
    )
    body = _upload(client, authed, case["id"], pdf).json()
    assert _run(db_session_factory, settings, body["job"]["id"]) == "partial"
    job = _job(client, case["id"], body["job"]["id"])
    assert job["error_code"] == "ocr_unavailable"
    assert "INSTALL_OCR=true" in job["error_detail"]
    result = job["result"]
    assert result["page_status_counts"] == {"text": 1, "image_only": 1}
    assert result["ocr"]["status"] == "unavailable"
    assert result["pages"][1]["ocr_status"] == "ocr_unavailable"
    assert any("no OCR text" in gap for gap in result["gaps"])
    assert [item["page_part"] for item in job["derived_evidence"]] == ["text_layer"]

    scanned_only = _upload(client, authed, case["id"], pdf_fixtures.image_only_pdf()).json()
    assert _run(db_session_factory, settings, scanned_only["job"]["id"]) == "partial"
    only = _job(client, case["id"], scanned_only["job"]["id"])
    assert only["result"]["document_state"] == "image_only"
    assert only["derived_evidence"] == []
    # Ordinary workspace operation continues.
    assert client.get(f"/api/v1/cases/{case['id']}/evidence").status_code == 200


@INTEGRATION
def test_ocr_output_is_a_separate_labelled_record(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Uses a labelled fake engine so the OCR bookkeeping is tested without Tesseract."""
    monkeypatch.setattr(
        documents,
        "ocr_availability",
        lambda _settings: documents.OcrAvailability(True, "fake-engine-0", ("eng", "tur")),
    )
    monkeypatch.setattr(documents, "render_page", lambda _s, _d, page: f"P5 {page}".encode())
    monkeypatch.setattr(
        documents, "ocr_image", lambda _s, image: f"Taranmış sayfa metni {image.decode()[3:]}"
    )
    case = create_case(client, authed)
    pdf = pdf_fixtures.build_pdf(
        [{"text": ["Embedded text layer on page one"]}, {"image": pdf_fixtures.noise_image()}]
    )
    body = _upload(client, authed, case["id"], pdf, ocr="if_needed").json()
    assert _run(db_session_factory, settings, body["job"]["id"]) == "completed"
    job = _job(client, case["id"], body["job"]["id"])
    parts = {item["page_part"]: item for item in job["derived_evidence"]}
    assert set(parts) == {"text_layer", "ocr_text"}
    ocr_detail = client.get(
        f"/api/v1/cases/{case['id']}/evidence/{parts['ocr_text']['id']}"
    ).json()["evidence"]
    assert ocr_detail["title"].endswith("OCR text")
    metadata = ocr_detail["collection_metadata"]
    assert metadata["text_origin"] == "ocr"
    assert metadata["engine"]["version"] == "fake-engine-0"
    assert metadata["page_map"][0]["page"] == 2
    assert "Taranmış sayfa metni 2" in _derived_text(
        settings, db_session_factory, parts["ocr_text"]["id"]
    )
    assert "Taranmış" not in _derived_text(settings, db_session_factory, parts["text_layer"]["id"])
    assert job["result"]["ocr_status_counts"] == {"ocr_text": 1}
    assert any("machine recognition" in item for item in job["result"]["limitations"])


@INTEGRATION
def test_page_and_ocr_limits_are_reported_as_gaps(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
    no_tesseract: None,
) -> None:
    case = create_case(client, authed)
    pdf = pdf_fixtures.text_pdf(*[[f"Synthetic page number {n} with text"] for n in range(1, 6)])
    body = _upload(client, authed, case["id"], pdf).json()
    assert _run(db_session_factory, settings, body["job"]["id"], document_max_pages=3) == "partial"
    job = _job(client, case["id"], body["job"]["id"])
    assert job["result"]["pages_total"] == 5
    assert job["result"]["pages_processed"] == 3
    assert any("first 3 of 5 pages" in gap for gap in job["result"]["gaps"])
    text = _derived_text(settings, db_session_factory, job["derived_evidence"][0]["id"])
    assert "page number 3" in text
    assert "page number 4" not in text


@INTEGRATION
def test_cancellation_keeps_finished_pages_and_reprocessing_replaces_derived_data(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
    monkeypatch: pytest.MonkeyPatch,
    no_tesseract: None,
) -> None:
    case = create_case(client, authed)
    pdf = pdf_fixtures.text_pdf(*[[f"Synthetic page {n} body text"] for n in range(1, 26)])
    body = _upload(client, authed, case["id"], pdf).json()
    job_id = body["job"]["id"]

    original = documents.pdf_command
    calls = {"extract": 0}

    def cancel_after_first_batch(
        settings_: Settings, arguments: list[str], document: bytes, **kwargs: Any
    ) -> dict[str, Any]:
        payload = original(settings_, arguments, document, **kwargs)
        if arguments[0] == "extract":
            calls["extract"] += 1
            if calls["extract"] == 1:
                response = client.post(
                    f"/api/v1/cases/{case['id']}/processing-jobs/{job_id}/cancel",
                    headers=browser_headers(authed),
                )
                assert response.status_code == 200, response.text
        return payload

    monkeypatch.setattr(documents, "pdf_command", cancel_after_first_batch)
    assert _run(db_session_factory, settings, job_id) == "canceled"
    monkeypatch.setattr(documents, "pdf_command", original)
    job = _job(client, case["id"], job_id)
    assert job["status"] == "canceled"
    assert job["result"]["pages_processed"] == documents_job.EXTRACT_BATCH_PAGES
    assert any("canceled" in gap for gap in job["result"]["gaps"])
    first_text_id = job["derived_evidence"][0]["id"]
    text = _derived_text(settings, db_session_factory, first_text_id)
    assert "Synthetic page 10 body" in text
    assert "Synthetic page 11 body" not in text

    again = client.post(
        f"/api/v1/cases/{case['id']}/evidence/{body['evidence']['id']}/processing",
        json={"job_type": "document_text", "ocr": "off"},
        headers=browser_headers(authed),
    )
    assert again.status_code == 202, again.text
    assert _run(db_session_factory, settings, again.json()["id"]) == "completed"
    with db_session_factory() as db:
        derived = list(
            db.scalars(
                select(EvidenceObject).where(
                    EvidenceObject.derived_from_evidence_id == uuid.UUID(body["evidence"]["id"])
                )
            )
        )
        assert db.get(EvidenceObject, uuid.UUID(first_text_id)) is None
    assert len(derived) == 1
    assert "Synthetic page 25 body" in _derived_text(
        settings, db_session_factory, str(derived[0].id)
    )
    files = [p for p in settings.evidence_storage_path.rglob("*") if p.is_file()]
    assert len(files) == 2  # the original and the current extracted text


@INTEGRATION
def test_worker_lost_mid_job_is_reclaimed_and_retries_are_bounded(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    case = create_case(client, authed)
    body = _upload(
        client, authed, case["id"], pdf_fixtures.text_pdf(["Retry page text here"])
    ).json()
    job_id = uuid.UUID(body["job"]["id"])

    def crash(*_args: Any, **_kwargs: Any) -> str:
        raise RuntimeError("worker bug")

    monkeypatch.setattr(documents_job, "process", crash)
    assert _run(db_session_factory, settings, str(job_id)) == "retried"
    with db_session_factory() as db:
        job = db.get(ProcessingJob, job_id)
        assert job is not None
        assert job.status == ProcessingStatus.QUEUED
        assert job.error_code == "internal_error"
    assert _run(db_session_factory, settings, str(job_id)) == "retried"
    assert _run(db_session_factory, settings, str(job_id)) == "failed"
    with db_session_factory() as db:
        job = db.get(ProcessingJob, job_id)
        assert job is not None
        assert job.status == ProcessingStatus.FAILED
        assert db.scalar(select(func.count()).select_from(EvidenceObject)) == 1


@INTEGRATION
def test_case_deletion_removes_imported_documents_and_derived_text(
    client: TestClient,
    settings: Settings,
    authed: str,
    db_session_factory: sessionmaker[Session],
    no_tesseract: None,
) -> None:
    from app.cases.deletion import DeletionContext, count_case_rows, execute_deletion

    case = create_case(client, authed)
    body = _upload(client, authed, case["id"], pdf_fixtures.text_pdf(["Deletion page text"])).json()
    assert _run(db_session_factory, settings, body["job"]["id"]) == "completed"
    waiting = _upload(client, authed, case["id"], pdf_fixtures.text_pdf(["Still queued text"]))
    assert waiting.status_code == 202
    requested = client.post(
        f"/api/v1/cases/{case['id']}/deletion",
        json={"confirm_title": case["title"]},
        headers=browser_headers(authed),
    )
    assert requested.status_code == 202, requested.text
    deletion_id = uuid.UUID(requested.json()["id"])
    storage = EvidenceStorage(settings.evidence_storage_path)
    assert (
        execute_deletion(
            DeletionContext(db_session_factory, storage, settings, "test"), deletion_id
        )
        == "completed"
    )
    with db_session_factory() as db:
        counts = count_case_rows(db, uuid.UUID(case["id"]))
    assert counts["processing_jobs"] == 0
    assert counts["evidence_objects"] == 0
    assert not storage.case_files_exist(uuid.UUID(case["id"]))


@pytest.mark.skipif(
    not documents.ocr_availability(
        Settings.model_construct(document_ocr_enabled=True, document_ocr_languages="eng")
    ).available,
    reason="real OCR needs Tesseract with English language data (OCR worker image)",
)
def test_real_tesseract_reads_a_scanned_page() -> None:
    settings = Settings.model_construct(
        document_ocr_enabled=True,
        document_ocr_languages="eng",
        document_ocr_dpi=200,
        document_ocr_max_pixels=25_000_000,
        document_ocr_page_timeout_seconds=60,
        document_parse_memory_mb=1024,
    )
    pdf = pdf_fixtures.scanned_text_pdf(["SYNTHETIC SCAN 2026", "Tracehollow OCR check"])
    image = documents.render_page(settings, pdf, 1)
    text = documents.ocr_image(settings, image)
    assert "SYNTHETIC" in text.upper()
