"""AES-256-GCM encryption for stored integration credentials (``cryptography`` library).

The 256-bit key comes from ``TRACEHOLLOW_CREDENTIAL_ENCRYPTION_KEY_FILE`` (64 hex characters,
generated by ``scripts/setup.sh``) and is never stored in PostgreSQL. Each value gets a fresh
96-bit nonce; the connector id and credential name are authenticated as associated data so a
ciphertext cannot be moved to another credential slot. ``key_id`` (a short digest of the key)
detects a key mismatch after restore or rotation without revealing the key.
"""

from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from app.config import Settings


class CredentialStoreUnavailableError(RuntimeError):
    """No usable encryption key is configured."""


class CredentialDecryptionError(RuntimeError):
    """The stored value cannot be decrypted with the configured key."""


@dataclass(frozen=True)
class Sealed:
    ciphertext: bytes
    nonce: bytes
    key_id: str


def _key(settings: Settings) -> bytes:
    secret = settings.credential_encryption_key
    if secret is None:
        raise CredentialStoreUnavailableError(
            "TRACEHOLLOW_CREDENTIAL_ENCRYPTION_KEY_FILE is not configured"
        )
    return bytes.fromhex(secret.get_secret_value())


def key_id_for(key: bytes) -> str:
    return hashlib.sha256(b"tracehollow-credential-key:" + key).hexdigest()[:16]


def _associated_data(connector_id: str, name: str) -> bytes:
    return f"tracehollow:{connector_id}:{name}".encode()


def seal(settings: Settings, connector_id: str, name: str, value: str) -> Sealed:
    key = _key(settings)
    nonce = os.urandom(12)
    ciphertext = AESGCM(key).encrypt(
        nonce, value.encode("utf-8"), _associated_data(connector_id, name)
    )
    return Sealed(ciphertext=ciphertext, nonce=nonce, key_id=key_id_for(key))


def open_sealed(
    settings: Settings, connector_id: str, name: str, ciphertext: bytes, nonce: bytes, key_id: str
) -> str:
    key = _key(settings)
    if key_id != key_id_for(key):
        raise CredentialDecryptionError(
            "The credential was encrypted with a different key; set it again."
        )
    try:
        plaintext = AESGCM(key).decrypt(nonce, ciphertext, _associated_data(connector_id, name))
    except InvalidTag as exc:
        raise CredentialDecryptionError("The stored credential failed authentication.") from exc
    return plaintext.decode("utf-8")
