#!/usr/bin/env python3
"""Measure how long the operations an analyst waits for take, on a synthetic dataset.

The script builds its own case through the HTTP API, times the requests the interface makes while
using that case, and prints the dataset, the machine and the measured percentiles. Nothing here is
a benchmark against other software and nothing is extrapolated: it reports what this machine did
with this dataset, so a reader can repeat it and compare.

Run it against a disposable stack, never against an installation holding real investigations:

    source <verification work dir>/env
    TRACEHOLLOW_PERF_USERNAME=acceptance-admin \
    TRACEHOLLOW_PERF_PASSWORD="$TRACEHOLLOW_ACCEPTANCE_PASSWORD" \
    python3 scripts/measure_performance.py --web-url http://localhost:3160

The case is titled "… (synthetic performance)" and is deleted at the end unless --keep is given.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import statistics
import subprocess
import sys
import time
import uuid
from collections.abc import Callable
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from phase1_acceptance import Session
from smoke_test import SmokeFailure, expect_status

CASE_TITLE = "Load and latency check (synthetic performance)"
ENTITY_TYPES = ("organization", "domain", "ip", "email", "platform_account")

EVIDENCE_TEMPLATE = """Synthetic record {index} (performance measurement, not a real source)

Domain:      node-{index}.example
Registrant:  Synthetic Holdings {group} Ltd
Registered:  2024-{month:02d}-{day:02d}
Address:     198.51.100.{octet} (documentation address)
Contact:     ops-{index}@node-{index}.example

This record exists only to give the performance measurement something to read. Every value is
generated; no real organisation, address or account is described.
"""


def percentile(values: list[float], fraction: float) -> float:
    ordered = sorted(values)
    if not ordered:
        return 0.0
    position = min(len(ordered) - 1, round(fraction * (len(ordered) - 1)))
    return ordered[position]


class Measurement:
    def __init__(self) -> None:
        self.rows: list[dict[str, Any]] = []

    def time(self, label: str, repeats: int, action: Callable[[int], Any]) -> None:
        action(0)  # warm the connection and any per-process cache
        samples: list[float] = []
        for attempt in range(repeats):
            started = time.perf_counter()
            action(attempt)
            samples.append((time.perf_counter() - started) * 1000)
        self.rows.append(
            {
                "operation": label,
                "samples": len(samples),
                "p50_ms": round(statistics.median(samples), 1),
                "p95_ms": round(percentile(samples, 0.95), 1),
                "max_ms": round(max(samples), 1),
            }
        )
        row = self.rows[-1]
        print(f"  {label:<46} p50 {row['p50_ms']:>7.1f} ms   p95 {row['p95_ms']:>7.1f} ms")


def machine() -> dict[str, str]:
    def run(*command: str) -> str:
        try:
            return subprocess.run(
                command, capture_output=True, text=True, timeout=10
            ).stdout.strip()
        except Exception:
            return "unknown"

    info = {
        "host": f"{platform.system()} {platform.release()} {platform.machine()}",
        "python": platform.python_version(),
        "docker": run("docker", "version", "--format", "{{.Server.Version}}") or "unknown",
    }
    if platform.system() == "Darwin":
        info["cpu"] = run("sysctl", "-n", "machdep.cpu.brand_string") or "unknown"
        memory = run("sysctl", "-n", "hw.memsize")
        info["memory"] = f"{int(memory) // (1024**3)} GiB" if memory.isdigit() else "unknown"
    return info


def seed(client: Session, case_id: str, args: argparse.Namespace) -> dict[str, Any]:
    api = f"/api/v1/cases/{case_id}"
    print(
        f"Seeding {args.evidence} evidence records, {args.entities} entities, "
        f"{args.relationships} relationships ..."
    )
    started = time.perf_counter()
    evidence_ids: list[str] = []
    for index in range(args.evidence):
        content = EVIDENCE_TEMPLATE.format(
            index=index,
            group=index % 7,
            month=(index % 12) + 1,
            day=(index % 28) + 1,
            octet=index % 254,
        ).encode()
        response = client.upload(
            case_id,
            content,
            f"synthetic-record-{index}.txt",
            kind="text",
            title=f"Synthetic record {index} (performance)",
            import_origin="Generated by scripts/measure_performance.py; not a real source.",
        )
        evidence_ids.append(
            expect_status(response, 201, "evidence imported").body["evidence"]["id"]
        )
    import_seconds = time.perf_counter() - started

    entity_ids: list[str] = []
    for index in range(args.entities):
        entity_type = ENTITY_TYPES[index % len(ENTITY_TYPES)]
        body = {
            "entity_type": entity_type,
            "display_name": f"Synthetic {entity_type} {index}",
            "identifiers": [{"identifier_type": "domain", "value": f"node-{index}.example"}]
            if entity_type == "domain"
            else [],
        }
        response = client.send("POST", f"{api}/entities", body)
        entity_ids.append(expect_status(response, 201, "entity created").body["id"])

    for index in range(args.relationships):
        source = entity_ids[index % len(entity_ids)]
        target = entity_ids[(index * 7 + 3) % len(entity_ids)]
        if source == target:
            continue
        client.send(
            "POST",
            f"{api}/relationships",
            {
                "source_entity_id": source,
                "target_entity_id": target,
                "predicate": "links_to",
                "description": "Generated for the performance measurement.",
                "supporting_evidence_ids": [evidence_ids[index % len(evidence_ids)]],
            },
        )
    return {
        "evidence_ids": evidence_ids,
        "entity_ids": entity_ids,
        "import_seconds": import_seconds,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--web-url", default="http://localhost:3160")
    parser.add_argument("--origin", default=None)
    parser.add_argument("--evidence", type=int, default=400)
    parser.add_argument("--entities", type=int, default=300)
    parser.add_argument("--relationships", type=int, default=450)
    parser.add_argument("--repeats", type=int, default=20)
    parser.add_argument("--keep", action="store_true", help="keep the case instead of deleting it")
    parser.add_argument("--json", type=Path, default=None, help="also write the results as JSON")
    args = parser.parse_args()
    args.origin = args.origin or args.web_url

    username = os.environ.get("TRACEHOLLOW_PERF_USERNAME")
    password = os.environ.get("TRACEHOLLOW_PERF_PASSWORD")
    if not username or not password:
        raise SmokeFailure("TRACEHOLLOW_PERF_USERNAME and TRACEHOLLOW_PERF_PASSWORD must be set")

    client = Session(args, username, password)
    case = expect_status(
        client.send(
            "POST",
            "/api/v1/cases",
            {
                "title": f"{CASE_TITLE} {uuid.uuid4().hex[:6]}",
                "purpose": "Measure request latency on a generated dataset.",
                "scope": "Synthetic records only. No real source is contacted.",
                "tags": ["synthetic-performance"],
            },
        ),
        201,
        "performance case created",
    ).body
    case_id = case["id"]
    api = f"/api/v1/cases/{case_id}"

    try:
        seeded = seed(client, case_id, args)
        deep_offset = max(0, args.evidence - 25)
        entity_id = seeded["entity_ids"][0]
        evidence_id = seeded["evidence_ids"][len(seeded["evidence_ids"]) // 2]

        print("\nMeasuring ...")
        measure = Measurement()
        measure.time(
            "Case list (20 per page)", args.repeats, lambda _: client.get("/api/v1/cases?limit=20")
        )
        measure.time("Case overview", args.repeats, lambda _: client.get(api))
        measure.time(
            "Evidence list, first page (25)",
            args.repeats,
            lambda _: client.get(f"{api}/evidence?limit=25"),
        )
        measure.time(
            f"Evidence list, last page (offset {deep_offset})",
            args.repeats,
            lambda _: client.get(f"{api}/evidence?limit=25&offset={deep_offset}"),
        )
        measure.time(
            "Evidence record with preview",
            args.repeats,
            lambda _: client.get(f"{api}/evidence/{evidence_id}/preview"),
        )
        measure.time(
            "Entity list (50)", args.repeats, lambda _: client.get(f"{api}/entities?limit=50")
        )
        measure.time(
            "Entity search by name",
            args.repeats,
            lambda i: client.get(f"{api}/entities?limit=25&q=Synthetic%20domain%20{i}"),
        )
        measure.time(
            "Relationship list (50)",
            args.repeats,
            lambda _: client.get(f"{api}/relationships?limit=50"),
        )
        measure.time(
            "Graph, bounded to 60 nodes",
            args.repeats,
            lambda _: client.get(f"{api}/graph?max_nodes=60&depth=1"),
        )
        measure.time(
            "Graph around one entity, depth 2",
            args.repeats,
            lambda _: client.get(f"{api}/graph?focus_entity_id={entity_id}&depth=2&max_nodes=60"),
        )
        measure.time("Timeline", args.repeats, lambda _: client.get(f"{api}/timeline"))
        measure.time(
            "Report selection lists",
            args.repeats,
            lambda _: client.get(f"{api}/reports/selectable"),
        )
        measure.time(
            "Report preview (25 evidence excerpts)",
            max(5, args.repeats // 4),
            lambda _: client.send(
                "POST",
                f"{api}/reports/html/preview",
                {
                    "include_case_purpose": True,
                    "evidence_ids": seeded["evidence_ids"][:25],
                    "entity_ids": seeded["entity_ids"][:10],
                },
            ),
        )

        results = {
            "dataset": {
                "evidence": args.evidence,
                "entities": args.entities,
                "relationships": args.relationships,
            },
            "machine": machine(),
            "import_seconds_total": round(seeded["import_seconds"], 1),
            "import_ms_per_record": round(
                seeded["import_seconds"] * 1000 / max(1, args.evidence), 1
            ),
            "measurements": measure.rows,
            "method": (
                "Each operation is called once to warm the connection, then timed over the listed "
                "number of calls from the host against the published API port. Times include HTTP, "
                "the API and PostgreSQL, but not browser rendering."
            ),
        }
        print(
            f"\nImports: {results['import_ms_per_record']} ms per record "
            f"({results['import_seconds_total']} s for {args.evidence} records)"
        )
        if args.json:
            args.json.write_text(json.dumps(results, indent=2))
            print(f"Wrote {args.json}")
        return 0
    finally:
        if not args.keep:
            client.send("POST", f"{api}/deletion", {"confirm_title": case["title"]})
            print("Requested deletion of the performance case.")


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SmokeFailure as error:
        print(f"FAILED: {error}", file=sys.stderr)
        raise SystemExit(1) from error
